# Generated by Django 5.2.17 on 2026-09-09 05:34

import apps.bookings.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_code', models.CharField(default=apps.bookings.models.generate_booking_code, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting payment'), ('PAYMENT_EXPIRED', 'Payment expired'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='AWAITING_PAYMENT', max_length=30)),
                ('total_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.bookings.models.default_expires_at)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('ROOM_RESERVATION', 'Room reservation'), ('FOOD_ORDER', 'Food order'), ('WELLNESS_SESSION', 'Wellness session'), ('OTOP_GOODS', 'OTOP goods')], max_length=30)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('item_title_snapshot', models.CharField(max_length=255)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_end_date', models.DateField(blank=True, null=True)),
                ('scheduled_time_slot', models.CharField(blank=True, max_length=50, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_items',
                'ordering': ('id',),
            },
        ),
    ]
