# Generated by Django 5.2.17 on 2026-09-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='entity_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
