# Generated by Django 5.2.17 on 2026-09-29 13:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('HOMESTAY', 'โฮมสเตย์ / ที่พักชุมชน'), ('FOOD', 'ร้านอาหารสุขภาพ'), ('WELLNESS', 'ศูนย์นวดแผนไทยและสปา'), ('OTOP', 'ศูนย์จำหน่ายสินค้า OTOP'), ('PHOTO_SPOT', 'จุดถ่ายรูป / จุดเช็คอินธรรมชาติ')], default='PHOTO_SPOT', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('address', models.TextField(blank=True, default='')),
                ('related_entity_id', models.CharField(blank=True, max_length=36, null=True)),
                ('qr_secret', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'map_locations',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_earned', models.IntegerField(default=0)),
                ('current_balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_points',
            },
        ),
        migrations.CreateModel(
            name='PassportStamp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified_method', models.CharField(default='QR_GPS', max_length=20)),
                ('stamped_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='community.maplocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_stamps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_stamps',
                'ordering': ('-stamped_at',),
                'unique_together': {('user', 'location')},
            },
        ),
    ]
