# Generated by Django 5.2.17 on 2026-09-09 05:34

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('subdistrict', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(db_index=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_time', models.TimeField(default=datetime.time(14, 0))),
                ('checkout_time', models.TimeField(default=datetime.time(12, 0))),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING_VERIFICATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='accommodations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Accommodations',
                'db_table': 'accommodations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('base_capacity', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_capacity', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_inventory', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodations.accommodation')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=1000)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.room')),
            ],
            options={
                'db_table': 'room_images',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoomPricingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('available_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='accommodations.room')),
            ],
            options={
                'db_table': 'room_pricing_calendars',
                'ordering': ('date',),
                'constraints': [models.UniqueConstraint(fields=('room', 'date'), name='uniq_room_pricing_date')],
            },
        ),
    ]
