# Generated by Django 5.2.17 on 2026-09-09 05:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('wellness_category', models.CharField(choices=[('LOW_SUGAR', 'Low sugar'), ('LOW_SODIUM', 'Low sodium'), ('ORGANIC', 'Organic'), ('HERBAL', 'Herbal'), ('VEGAN', 'Vegan')], max_length=50)),
                ('calorie_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='food_menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Food menus',
                'db_table': 'food_menus',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WellnessService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_capacity_per_session', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='wellness_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wellness services',
                'db_table': 'wellness_services',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='WellnessTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='services.wellnessservice')),
            ],
            options={
                'db_table': 'wellness_time_slots',
                'ordering': ('slot_date', 'start_time'),
                'constraints': [models.UniqueConstraint(fields=('service', 'slot_date', 'start_time'), name='uniq_wellness_service_slot')],
            },
        ),
    ]
