"""
DRF serializers for the OTOP API (Step 3, otop slice).

WHY explicit fields instead of "__all__":
- owner is injected by the view from the authenticated token, never accepted
  from the client (anti-impersonation / IDOR hardening).
- sku is auto-generated by OTOPProduct.save() (model docstring), so it must be
  read-only here: a client cannot send a duplicate SKU nor is it required.
- category is a TextChoices column; DRF maps it to a ChoiceField, giving 400
  on values outside the four OTOP categories automatically.
- price keeps min_value=0.01 so the API rejects zero/negative BEFORE the DB.
"""
from decimal import Decimal

from rest_framework import serializers

from .models import OTOPProduct


class OTOPProductSerializer(serializers.ModelSerializer):
    """OTOPProduct row; owner is injected by the view, never read from body."""

    price = serializers.DecimalField(
        max_digits=10, decimal_places=2, min_value=Decimal("0.01")
    )
    # PositiveIntegerField already maps to IntegerField(min_value=0); make it
    # explicit so creating with a negative stock is a 400, not an IntegrityError.
    stock_quantity = serializers.IntegerField(min_value=0)

    class Meta:
        model = OTOPProduct
        fields = (
            "id",
            "name",
            "category",
            "description",
            "price",
            "stock_quantity",
            "sku",
            "is_active",
        )
        read_only_fields = ("id", "sku")


class OTOPStockAdjustSerializer(serializers.Serializer):
    """POST /api/v1/otop/{id}/stock/ payload.

    A signed delta: +N restocks, -N removes stock. The server applies it to
    the CURRENT stock_quantity and rejects a result below zero, so the vendor
    can never drive inventory negative through this endpoint.
    """

    delta = serializers.IntegerField()
