# Generated by Django 5.2.17 on 2026-09-08 12:25

import apps.authentication.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, help_text='Auto-generated from email; kept only for spec compatibility.', max_length=150, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone_number', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('TOURIST', 'Tourist'), ('HOMESTAY_OWNER', 'Homestay Owner'), ('RESTAURANT_OWNER', 'Restaurant Owner'), ('WELLNESS_OWNER', 'Wellness Owner'), ('OTOP_OWNER', 'OTOP Owner'), ('COMMUNITY_ADMIN', 'Community Admin'), ('SUPER_ADMIN', 'Super Admin')], default='TOURIST', max_length=30)),
                ('google_sub_id', models.CharField(blank=True, db_index=True, help_text="Stable Google 'sub' claim. NULL until the user signs in with Google.", max_length=255, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.authentication.managers.UserManager()),
            ],
        ),
    ]
