# Generated by Django 5.2.17 on 2026-10-03 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('business_category', models.CharField(choices=[('HOMESTAY', 'โฮมสเตย์ / ที่พักชุมชน'), ('RESTAURANT', 'ร้านอาหารเพื่อสุขภาพ'), ('WELLNESS', 'บริการสุขภาพ & สปา'), ('OTOP', 'สินค้า OTOP ชุมชน')], default='HOMESTAY', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('google_maps_url', models.URLField(blank=True, default='', max_length=500)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('opening_hours', models.CharField(blank=True, default='08:00 - 18:00 น.', max_length=150)),
                ('cover_image_url', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'อยู่ระหว่างการตรวจสอบ (Pending Review)'), ('APPROVED', 'อนุมัติแล้ว (Approved)'), ('REJECTED', 'ไม่ผ่านการอนุมัติ (Rejected)')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchant_profiles',
                'ordering': ('-created_at',),
            },
        ),
    ]
