"use client";
import { useState } from "react";
import { Globe,LocateFixed,LogOut,Trash2,ShieldCheck } from "lucide-react";
import { LanguageToggle } from "@/components/ui/language-toggle";
import { useAuth } from "@/hooks/use-auth";
import { useTravelCopy } from "@/components/travel/travel-shell";
import { PageHeading } from "@/components/travel/Primitives";
import { LocationConsent } from "@/components/travel/LocationConsent";
import { deleteLocationHistory } from "@/lib/api/experience";
export default function Settings(){const copy=useTravelCopy();const {user,logout}=useAuth();const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState(false);const [message,setMessage]=useState("");
 async function remove(){setBusy(true);try{await deleteLocationHistory();setMessage(copy("ลบประวัติตำแหน่งของคุณแล้ว","Your location history has been deleted."));setConfirm(false);}catch{setMessage(copy("ลบไม่สำเร็จ โปรดลองอีกครั้ง","Could not delete. Please try again."));}finally{setBusy(false);}}
 return <div className="wt-page" style={{maxWidth:720}}><PageHeading eyebrow="YOUR PREFERENCES" title={copy("ตั้งค่าการใช้งาน","Make yourself at home")} description={copy("จัดการภาษาและข้อมูลตำแหน่งที่คุณเลือกแชร์","Manage your language and the location information you choose to share.")}/><section className="wt-panel wt-actions"><Globe size={20}/><h2>{copy("ภาษาของเว็บไซต์","Site language")}</h2><LanguageToggle/></section><section className="wt-section wt-panel"><h2 className="wt-actions"><LocateFixed size={20}/>{copy("ข้อมูลตำแหน่ง","Location information")}</h2><p className="wt-muted">{copy("ไม่มีการติดตามตำแหน่งต่อเนื่อง การลบประวัติไม่เปลี่ยนสิทธิ์ตำแหน่งในเบราว์เซอร์ คุณยกเลิกสิทธิ์ได้จากการตั้งค่าเว็บไซต์ของเบราว์เซอร์","Continuous location tracking is off. Deleting records does not change browser permissions. Revoke location permission in your browser’s site settings.")}</p>{user&&<div style={{marginTop:16}}>{confirm?<div className="wt-actions"><p>{copy("ยืนยันลบประวัติตำแหน่งทั้งหมดของคุณ?","Delete all your location records?")}</p><button disabled={busy} onClick={()=>void remove()} className="wt-button">{copy("ยืนยันลบ","Confirm deletion")}</button><button disabled={busy} onClick={()=>setConfirm(false)} className="wt-button secondary">{copy("ยกเลิก","Cancel")}</button></div>:<button className="wt-button secondary" onClick={()=>setConfirm(true)}><Trash2 size={16}/>{copy("ลบประวัติตำแหน่งของฉัน","Delete my location history")}</button>}</div>}<p role="status" className="wt-muted">{message}</p></section><LocationConsent/><section className="wt-section wt-panel"><h2 className="wt-actions"><ShieldCheck size={20}/>{copy("ความเป็นส่วนตัว","Privacy")}</h2><p className="wt-muted">{copy("การแชร์ตำแหน่งเป็นทางเลือก เลือกใช้บริการได้แม้ไม่อนุญาต ระบบจะขอความยินยอมใหม่ทุกครั้งที่คุณกดแชร์","Location sharing is optional. You can browse without it. The site asks for consent each time you choose to share.")}</p></section>{user&&<button className="wt-button secondary wt-section" onClick={()=>logout()}><LogOut size={17}/>{copy("ออกจากระบบ","Sign out")}</button>}</div>;
}
