# Generated by Django 5.2.17 on 2026-09-09 05:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_channel', models.CharField(choices=[('PROMPTPAY_QR', 'PromptPay QR'), ('CREDIT_CARD', 'Credit card')], max_length=30)),
                ('gateway_charge_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('qr_raw_string', models.TextField(blank=True, help_text='Raw EMVCo PromptPay payload.', null=True)),
                ('qr_image_url', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_response_log', models.JSONField(blank=True, default=dict, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='bookings.booking')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
