# Generated by Django 5.2.17 on 2026-09-09 05:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_response_log',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='qr_image_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='qr_raw_string',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payee_account_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='payee_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payee_bank',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_channel',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer (slip check)')], default='BANK_TRANSFER', max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='slips/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('amount_seen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING_CHECK', 'Pending check'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_CHECK', max_length=30)),
                ('provider_response_log', models.JSONField(blank=True, default=dict, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='slips', to='payments.payment')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_slips',
                'ordering': ('-uploaded_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'VERIFIED'), models.Q(('provider_reference', ''), _negated=True)), fields=('provider_reference',), name='uniq_verified_slip_reference')],
            },
        ),
    ]
