"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation } from "@tanstack/react-query";
import { ArrowRight,ArrowLeft,Loader2,Leaf } from "lucide-react";
import { submitHealthAssessment } from "@/lib/api/ai";
import { extractErrorMessage } from "@/lib/api/errors";
import { PageHeading } from "@/components/travel/Primitives";
import { useTravelCopy } from "@/components/travel/travel-shell";
export default function HealthPage(){
 const copy=useTravelCopy();const router=useRouter();const [step,setStep]=useState(0);const [height,setHeight]=useState("");const [weight,setWeight]=useState("");const [age,setAge]=useState("");const [gender,setGender]=useState("male");const [goal,setGoal]=useState("STRESS_RELIEF");const [diet,setDiet]=useState<string[]>([]);const [consent,setConsent]=useState(false);
 const goals=[{value:"STRESS_RELIEF",label:copy("พักผ่อนและคลายความเครียด","Rest & relaxation")},{value:"DETOX",label:copy("สนใจอาหารใยอาหารสูง","Explore fibre-rich food")},{value:"BLOOD_SUGAR_CONTROL",label:copy("สนใจเมนูหวานน้อย","Explore lower-sugar food")},{value:"FATIGUE_RECOVERY",label:copy("พักจากความเหนื่อยล้า","Take a break from fatigue")}];
 const mutation=useMutation({mutationFn:submitHealthAssessment,onSuccess:res=>{sessionStorage.setItem("ai_recommendation_result",JSON.stringify(res.data));router.push("/ai-recommendation");}});
 const steps=[copy("ข้อมูลพื้นฐาน","About you"),copy("ความสนใจ","Preferences"),copy("ตรวจสอบ","Review")];
 return <div className="wt-page" style={{maxWidth:760}}><PageHeading eyebrow="A LITTLE MORE YOU" title={copy("ออกแบบวันพักผ่อนของคุณ","Make your next break your own")} description={copy("ตอบทีละขั้นเพื่อประกอบคำแนะนำด้านการท่องเที่ยว ไม่ใช่การวินิจฉัยสุขภาพ","Share a little about yourself for travel suggestions, not a medical diagnosis.")}/><ol className="wt-steps">{steps.map((s,i)=><li key={s} aria-current={step===i?"step":undefined}>{i+1}. {s}</li>)}</ol>
 <form className="wt-form wt-panel" onSubmit={e=>{e.preventDefault();if(step<2){setStep(step+1);return;}if(consent)mutation.mutate({height_cm:Number(height),weight_kg:Number(weight),age:Number(age),gender,health_goal:goal,dietary_restrictions:diet,lifestyle:"MODERATE"});}}>
 {step===0&&<><h2>{copy("ข้อมูลพื้นฐานของคุณ","A little about you")}</h2><label>{copy("ส่วนสูง (ซม.)","Height (cm)")}<input type="number" min="50" max="250" step="0.1" required value={height} onChange={e=>setHeight(e.target.value)}/></label><label>{copy("น้ำหนัก (กก.)","Weight (kg)")}<input type="number" min="20" max="300" step="0.1" required value={weight} onChange={e=>setWeight(e.target.value)}/></label><label>{copy("อายุ (ปี)","Age (years)")}<input type="number" min="1" max="120" required value={age} onChange={e=>setAge(e.target.value)}/></label><label>{copy("เพศสำหรับสูตรคำนวณของระบบ","Sex used by the calculation")}<select value={gender} onChange={e=>setGender(e.target.value)}><option value="male">{copy("ชาย","Male")}</option><option value="female">{copy("หญิง","Female")}</option></select></label><p className="wt-muted">{copy("หากไม่สะดวกให้ข้อมูล คุณสามารถเลือกบริการได้โดยตรงจากเมนูสำรวจ","If you prefer not to share this information, browse services directly from Explore.")}</p></>}
 {step===1&&<><label>{copy("ทริปนี้อยากพักผ่อนแบบไหน","What would you like from this trip?")}<select value={goal} onChange={e=>setGoal(e.target.value)}>{goals.map(g=><option key={g.value} value={g.value}>{g.label}</option>)}</select></label><fieldset><legend>{copy("ความสนใจด้านอาหาร (เลือกได้หลายข้อ)","Food preferences (choose any)")}</legend><div className="wt-actions" style={{marginTop:12}}>{[{id:"vegan",th:"วีแกน",en:"Vegan"},{id:"low_sodium",th:"โซเดียมต่ำ",en:"Low sodium"},{id:"low_sugar",th:"หวานน้อย",en:"Low sugar"},{id:"organic",th:"ออร์แกนิก",en:"Organic"}].map(d=><button type="button" className="wt-chip" key={d.id} aria-pressed={diet.includes(d.id)} onClick={()=>setDiet(old=>old.includes(d.id)?old.filter(x=>x!==d.id):[...old,d.id])}>{copy(d.th,d.en)}</button>)}</div></fieldset></>}
 {step===2&&<><h2>{copy("ตรวจสอบก่อนส่งข้อมูล","Review before sending")}</h2><dl className="wt-detail"><dt>{copy("ส่วนสูง / น้ำหนัก / อายุ","Height / weight / age")}</dt><dd>{height} cm · {weight} kg · {age}</dd><dt>{copy("เป้าหมาย","Goal")}</dt><dd>{goals.find(g=>g.value===goal)?.label}</dd><dt>{copy("ความสนใจอาหาร","Food preferences")}</dt><dd>{diet.length?diet.join(", "):copy("ไม่ได้เลือก","None selected")}</dd></dl><p className="wt-muted">{copy("ระบบจะบันทึกข้อมูลสุขภาพที่ส่งในบัญชีของคุณ และอาจส่งข้อมูลที่จำเป็นให้ผู้ให้บริการ AI ที่ระบบตั้งค่าไว้เพื่อจัดทำคำแนะนำ โดยไม่มีการส่งพิกัดตำแหน่งจากแบบฟอร์มนี้","Submitted health information is saved to your account. Necessary information may be sent to configured AI providers to generate suggestions. This form does not send your location.")}</p><label className="wt-check" style={{display:"flex"}}><input style={{width:20,minHeight:20}} type="checkbox" checked={consent} required onChange={e=>setConsent(e.target.checked)}/><span>{copy("ยินยอมให้ประมวลผลข้อมูลข้างต้นเพื่อรับคำแนะนำ","I agree to the processing above to receive suggestions.")}</span></label></>}
 {mutation.isError&&<p role="alert" className="wt-error">{extractErrorMessage(mutation.error)}</p>}
 <div className="wt-actions">{step>0&&<button className="wt-button secondary" disabled={mutation.isPending} type="button" onClick={()=>setStep(step-1)}><ArrowLeft size={16}/>{copy("ย้อนกลับ","Back")}</button>}<button className="wt-button" disabled={mutation.isPending||(step===2&&!consent)} type="submit">{mutation.isPending?<Loader2 className="animate-spin" size={17}/>:step===2?<Leaf size={17}/>:<ArrowRight size={17}/>} {step===2?copy("ขอคำแนะนำทริป","Get trip suggestions"):copy("ถัดไป","Continue")}</button></div>
 </form></div>;
}
