# Generated by Django 5.2.17 on 2026-09-09 05:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTOPProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('HERBAL_PRODUCT', 'Herbal product'), ('TEXTILE', 'Textile'), ('PROCESSED_FOOD', 'Processed food'), ('CRAFT', 'Craft')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='otop_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'OTOP products',
                'db_table': 'otop_products',
                'ordering': ('name',),
            },
        ),
    ]
